"""allow clarification action history

Revision ID: 99de8f7cab4c
Revises: 9c9b975bf60d
Create Date: 2026-07-30 19:28:38.087545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99de8f7cab4c'
down_revision: Union[str, Sequence[str], None] = '9c9b975bf60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_pending_actions_conversation_id'), table_name='conversation_pending_actions')
    op.create_index(op.f('ix_conversation_pending_actions_conversation_id'), 'conversation_pending_actions', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_pending_actions_conversation_id'), table_name='conversation_pending_actions')
    op.create_index(op.f('ix_conversation_pending_actions_conversation_id'), 'conversation_pending_actions', ['conversation_id'], unique=True)
    # ### end Alembic commands ###
