"""add pre rag agent tables

Revision ID: 9c9b975bf60d
Revises: h1i2j3k4l5m6
Create Date: 2026-07-30 18:48:42.132335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c9b975bf60d'
down_revision: Union[str, Sequence[str], None] = 'h1i2j3k4l5m6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_chunk_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('normalized_term', sa.String(length=500), nullable=False),
    sa.Column('term_type', sa.String(length=50), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_chunk_id'], ['resource_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_id', 'resource_chunk_id', 'normalized_term', name='uq_resource_terms_owner_chunk_term')
    )
    op.create_index(op.f('ix_resource_terms_created_by_id'), 'resource_terms', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_resource_terms_is_active'), 'resource_terms', ['is_active'], unique=False)
    op.create_index(op.f('ix_resource_terms_normalized_term'), 'resource_terms', ['normalized_term'], unique=False)
    op.create_index(op.f('ix_resource_terms_resource_chunk_id'), 'resource_terms', ['resource_chunk_id'], unique=False)
    op.create_index(op.f('ix_resource_terms_resource_id'), 'resource_terms', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_terms_term_type'), 'resource_terms', ['term_type'], unique=False)
    op.create_table('conversation_pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('original_user_text', sa.Text(), nullable=False),
    sa.Column('uncertain_term', sa.String(length=500), nullable=False),
    sa.Column('candidate_term', sa.String(length=500), nullable=False),
    sa.Column('candidate_type', sa.String(length=80), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_pending_actions_api_key_id'), 'conversation_pending_actions', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_conversation_pending_actions_conversation_id'), 'conversation_pending_actions', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_pending_actions_created_by_id'), 'conversation_pending_actions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_conversation_pending_actions_expires_at'), 'conversation_pending_actions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_conversation_pending_actions_status'), 'conversation_pending_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_pending_actions_status'), table_name='conversation_pending_actions')
    op.drop_index(op.f('ix_conversation_pending_actions_expires_at'), table_name='conversation_pending_actions')
    op.drop_index(op.f('ix_conversation_pending_actions_created_by_id'), table_name='conversation_pending_actions')
    op.drop_index(op.f('ix_conversation_pending_actions_conversation_id'), table_name='conversation_pending_actions')
    op.drop_index(op.f('ix_conversation_pending_actions_api_key_id'), table_name='conversation_pending_actions')
    op.drop_table('conversation_pending_actions')
    op.drop_index(op.f('ix_resource_terms_term_type'), table_name='resource_terms')
    op.drop_index(op.f('ix_resource_terms_resource_id'), table_name='resource_terms')
    op.drop_index(op.f('ix_resource_terms_resource_chunk_id'), table_name='resource_terms')
    op.drop_index(op.f('ix_resource_terms_normalized_term'), table_name='resource_terms')
    op.drop_index(op.f('ix_resource_terms_is_active'), table_name='resource_terms')
    op.drop_index(op.f('ix_resource_terms_created_by_id'), table_name='resource_terms')
    op.drop_table('resource_terms')
    # ### end Alembic commands ###
